### ISSUE TITLE
Provide DeviceType enum for built in Android NFC reader

### ISSUE THREAD

**Issue by pratikpwr** [BreX900/mek-packages#10]
Currently, Device Type enum values don't consists built-in Android NFC reader please add this

**Comment by SimoneBressan** [comment]
What do you mean with "don't consists built-in"?

**Comment by pratikpwr** [comment]
For Apple devices, DeviceType enum has `DeviceType.appleBuiltIn` value. So please add for android devices as well, so it will be easy to write device specific code.

**Comment by SimoneBressan** [comment]
There is no equivalent in the Android SDK for `DeviceType.appleBuiltIn`
https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.models/-device-type/index.html

If you can give me some more information based on the official android doc, maybe I can help you
