### ISSUE TITLE
StatementDescriptorSuffix

### ISSUE THREAD

**Issue by SERDARPINAR** [BreX900/mek-packages#11]
hi there..how are you.. 

how can i add StatementDescriptorSuffix on createpayment intent. do you have supportt this ? thankss.

**Comment by BreX900** [comment]
My goal for now is to fix the bugs in the current version of the package and release a new version supporting the android/ios sdk for version 3.0.0
I will probably include this request in the next major

**Comment by SERDARPINAR** [comment]
hi.. thank you.. im waiting.. butnnow i will try adding parameters..

**Comment by BreX900** [comment]
I have released version `3.0.0-dev` supporting what you requested.
Read the changelog for all breaking changes. Thanks

**Comment by SERDARPINAR** [comment]
hi.thank you.. but still i seeing 2.1.4 on pub.dev

**Comment by BreX900** [comment]
you can select the prerelease by pressing next to the version. Here is the direct link

https://pub.dev/packages/mek_stripe_terminal/versions/3.0.0-dev

**Comment by SERDARPINAR** [comment]
hi ...ok. i will do. thanks.
