### ISSUE TITLE
tap to pay

### ISSUE THREAD

**Issue by SERDARPINAR** [BreX900/mek-packages#12]
hi mate.. im trying for tap to pay(iphone).. but im getting error.but every settings is true. can you help. me

Operation not permitted. Verify the app has the necessary entitlements and that the application bundle is valid., Error Domain=com.stripe-terminal Code=2900 "Operation not permitted. Verify the app has the necessary entitlements and that the application bundle is valid." UserInfo={com.stripe-terminal:ReaderMessage=Error usually caused by an entitlement issue, an invalid application bundle, a configuration issue, or a token issue., NSLocalizedDescription=Operation not permitted. Verify the app has the necessary entitlements and that the application bundle is valid., com.stripe-terminal:Message=Operation not permitted. Verify the app has the necessary entitlements and that the application bundle is valid

**Comment by SERDARPINAR** [comment]
now error is

"This feature is currently not available for the selected reader." UserInfo={NSLocalizedDescription=This feature is currently not available for the selected reader., com.stripe-terminal:Message=This feature is currently not available for the selected reader.}

**Comment by BreX900** [comment]
Please post the error with more information, such as the entire error with the stacktrace, a piece of code where the error is generated, whether you are using an android or ios device and the phone model.
I remember that not all Android phones support stripe terminal, see the official doc about it

**Comment by SERDARPINAR** [comment]
hi. iphone 12 device. and i saw the supportted device. ios 17..  error accuared on connet to local device.

**Comment by BreX900** [comment]
Honestly, it doesn't seem like an error with my plugin, but more like a configuration problem
Try and see [Tap to Pay](https://stripe.com/docs/terminal/payments/connect-reader?reader-type=tap-to-pay) and [Configure plugin (STEP 2)](https://stripe.com/docs/terminal/payments/setup-integration?terminal-sdk-platform=ios#configure)

**Comment by BreX900** [comment]
I am closing for lack of interaction/information

**Comment by SERDARPINAR** [comment]
hi.mate..sorry for late.. i found the issue. issue is on apple developer idenntifier . i cant enable tap to pay on my identifiers. but i doesnot find the solve. Apple told me "enable on the additional capability tab" . but i doesnt see this tab on my account.

**Comment by BreX900** [comment]
Maybe this link could be useful to you
https://stripe.com/docs/terminal/payments/setup-reader/tap-to-pay?platform=ios#entitlements-build-file

**Comment by BreX900** [comment]
Also take a look at [this page](https://developer.apple.com/tap-to-pay).
I see they write this here on Get started paragraph 
> Request the [Tap to Pay on iPhone Entitlement](https://developer.apple.com/contact/request/contactless-payments/) from Apple.

**Comment by SERDARPINAR** [comment]
hi again
<img width="1680" alt="Screenshot 2023-10-10 at 19 13 03" src="https://github.com/BreX900/mek-packages/assets/79941770/68287917-abd7-4928-a021-f718bed701ab">

**Comment by BreX900** [comment]
That doesn't depend on the plugin, it could depend on your account permissions or something else, I don't know how to help you beyond that
You can try contacting apple/stripe support

**Comment by SERDARPINAR** [comment]
yes mate.you are right.  and i guess this link will be fix my issue.
 (Request the [Tap to Pay on iPhone Entitlement](https://developer.apple.com/contact/request/contactless-payments/) from Apple.)

but it's very interesting. Why is extra permission required for this event?
now im waiting the response from apple..

thank you ..thank you..thank you
