### ISSUE TITLE
mek_stripe_terminal/StripeTerminalPlugin.swift:255: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by jacopofranza** [BreX900/mek-packages#16]
Getting fatal error and crash (version 3.0.0-dev.1) during accepting payment method with:

mek_stripe_terminal/StripeTerminalPlugin.swift:255: Fatal error: Unexpectedly found nil while unwrapping an Optional value
mek_stripe_terminal/StripeTerminalPlugin.swift:255: Fatal error: Unexpectedly found nil while unwrapping an Optional value
thread 9, queue = 'com.apple.root.user-initiated-qos.cooperative', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
    frame #0: 0x00000001a6d90818 libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`:
->  0x1a6d90818 <+0>: ret    
libswiftCore.dylib`:
    0x1a6d9081c <+0>: b      0x1a6d90818               ; _swift_runtime_on_report
libswiftCore.dylib`:
    0x1a6d90820 <+0>: adrp   x8, 376357
    0x1a6d90824 <+4>: ldrb   w0, [x8, #0x434]
Target 0: (Runner) stopped.

**Comment by BreX900** [comment]
Plugin (mek_stripe_terminal) version? 
In version 3.0.0-dev.1 this bug has been fixed, could you try?

**Comment by jacopofranza** [comment]
I'm already in the latest version

**Comment by BreX900** [comment]
Sorry, I didn't realize you wrote the version

Can you tell me what values you used to create the PaymentIntent?
I don't know how to simulate the bug honestly

**Comment by jacopofranza** [comment]
Sorry man, my fault, the problem was because I was confirming a payment intent before collecting a payment method. But maybe you would add a check in your plugin just to verify a payment intent status and avoid crash.

**Comment by BreX900** [comment]
Yes, error management is the last important thing I need to do, the point is that it is different between Android and iOS and there are too many errors
On iOS I haven't yet fully understood what errors the stripe terminal SDK throws

**Comment by vipinkashyap** [comment]
Here's a list of all the exceptions. Please let me know if you have an elegant way to handle all/most of these . The exception is thrown differently on android and ios 

[IOS Exceptions](https://stripe.dev/stripe-terminal-ios/docs/Enums/SCPError.html)
[Android Exceptions](https://stripe.dev/stripe-terminal-android/v1/com/stripe/stripeterminal/model/external/TerminalException.TerminalErrorCode.html)

**Comment by jacopofranza** [comment]
Putting together all the exceptions and creating a common enum could be a solution and it seems like a long and repetitive job to feed to chat gpt, if you want I can try @BreX900

**Comment by BreX900** [comment]
Yes, it is my intention to provide an enum with the same exception list between Android and iOS.
For now the solution I recommend is:
```dart
    try {
      final paymentIntentWithPaymentMethod = await terminal.collectPaymentMethod(paymentIntent)
      _showSnackBar('Payment method collected!');
    } on TerminalException catch (exception) {
      switch (exception.rawCode) {
        // TODO: map error codes from swift/android and unify them for dart
        case '2020' || 'cancelled':
          _showSnackBar('Collecting Payment method is cancelled!');
        default:
          rethrow;
      }
    }
```
As also shown in the example.

It could certainly be useful to have a "map" with a list of Android and iOS error codes for Dart. It will take some time, thanks for your patience

**Comment by jacopofranza** [comment]
> Here's a list of all the exceptions. Please let me know if you have an elegant way to handle all/most of these . The exceptions are thrown differently on android and ios
> 
> [IOS Exceptions](https://stripe.dev/stripe-terminal-ios/docs/Enums/SCPError.html) [Android Exceptions](https://stripe.dev/stripe-terminal-android/v1/com/stripe/stripeterminal/model/external/TerminalException.TerminalErrorCode.html)

New Android errors are these: [TerminalExceptions](https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.models/-terminal-exception/-terminal-error-code/index.html)

**Comment by BreX900** [comment]
Version `3.0.0`, fixes this bug and has ios/android errors mapped to a single enum.
I'm closing the issue. If you find other problems in this regard, please open another issue
