### ISSUE TITLE
dongle restarts on readReusableCard()

### ISSUE THREAD

**Issue by laloriru** [BreX900/mek-packages#26]
Hello
I'm using the BBPOS Chipper 2X BT. I connect to it via bluetooth successfully, but once I click a button I use for the method readReusableCard(), nothing happens, not even an error log is displayed. 
Is it possible to track the error?
Once the dongle is connected it should be able to read the debt card on the dongle?
thanks a lot

**Comment by BreX900** [comment]
Could you try with the latest version of the plugin `3.0.0`?

**Comment by laloriru** [comment]
I updated and successfully connected to the reader. But readReusableCard() doesn't exist anymore on version 3.0.0 . The only thing I need so far, is getting the credit/debit card (number/exp date) without processing the payment on Stripe. Is that possible? thanks a lot

**Comment by BreX900** [comment]
Yes has been removed, please check the CHANGELOG.md file:
- refactor: Terminal.readReusableCard has been removed. This functionality is replaced by [Setup Intents](https://stripe.com/docs/terminal/features/saving-cards/save-cards-directly?terminal-sdk-platform=android).
