### ISSUE TITLE
Missing Plugin Exception while running release build in Real Device while it works in Android Emulator

### ISSUE THREAD

**Issue by pratikpwr** [BreX900/mek-packages#33]
I am able to initialize stripe terminal properly in Android Emulator but it fails in Real Device
I am getting only below Error
`MissingPluginException(No implementation found for method init on channel StripeTerminalPlatform)`

**Comment by BreX900** [comment]
try `flutter clean && flutter pub get`

**Comment by BreX900** [comment]
@pratikpwr Can you close the issue if the problem has been resolved?
