### ISSUE TITLE
In Simulated mode Transaction Fails

### ISSUE THREAD

**Issue by pratikpwr** [BreX900/mek-packages#35]
In Package version `3.1.0`  the simualted sechnario for payment processsing is failing with following error

`com.stripe.stripeterminal.external.models.TerminalException: This transaction requires a PIN. In testmode, using a physical test card with designated amount ending values produce specific decline responses. See https://stripe.com/docs/terminal/references/testing#physical-test-cards for details.`

`ApiError(error=InnerError(charge=ch_3O1pmCPx7XPnEVCK05rNOvvO, code=online_or_offline_pin_required, declineCode=online_or_offline_pin_required, docUrl=null, message=This transaction requires a PIN. In testmode, using a physical test card with designated amount ending values produce specific decline responses. See https://stripe.com/docs/terminal/references/testing#physical-test-cards for details., param=null, paymentIntent=PaymentIntent(id=pi_3O1pmCPx7XPnEVCK0P13G5Fk, amount=8103, amountCapturable=0, amountReceived=0, application=null, applicationFeeAmount=0, canceledAt=0, cancellationReason=null, captureMethod=manual, charges=ChargesList(data=[Charge(id=ch_3O1pmCPx7XPnEVCK05rNOvvO, amount=8103, amountRefunded=0, application=null, applicationFee=null, applicationFeeAmount=0, balanceTransaction=null, captured=false, created=1697458810, currency=usd, customer=null, description=null, dispute=null, failureCode=online_or_offline_pin_required, failureMessage=This transaction requires a PIN.`

This works properly in an older version `2.1.4` 
I am connected to a Simulated  Chipper2X reader and using `isSimulated` as true while discovering readers

**Comment by BreX900** [comment]
It's correct. Read the error:
```
This transaction requires a PIN. In testmode, using a physical test card with designated amount ending values produces specific decline responses. See https://stripe.com/docs/terminal/references/testing#physical-test-cards for details.
```

**Comment by BreX900** [comment]
@pratikpwr Can you close the issue if the problem has been resolved?

**Comment by pratikpwr** [comment]
Ohh got it, Thanks I tried that 2-3 times with different amounts but after reading docs got clarity

**Comment by pratikpwr** [comment]
Ohh got it, Thanks I tried that 2-3 times with different amounts but after reading docs got clarity
