### ISSUE TITLE
MissingPluginExcepition - Andorid Embedded Board ZC-3566

### ISSUE THREAD

**Issue by kekko7072** [BreX900/mek-packages#38]
Hi, i'm trying using this package with a flutter app on an andorid 11 device for TV monitors.
![IMG_4660](https://github.com/BreX900/mek-packages/assets/32552589/a3693f8f-f478-49c5-8609-0b36acf06309)

I used the example and successfully run it on a mobile device (Tablet), now when i try it on this device it return the error *No implementatio found for method init on channel mek_stripe_terminal*:
![IMG_4661](https://github.com/BreX900/mek-packages/assets/32552589/790826d1-128d-476b-ae7c-2e4fc4467983)

Any solution / workaround ?

**Comment by BreX900** [comment]
Sorry for the delay.
Usually that error is thrown when there is an error on the init method that is not handleable by the plugin. I've encountered this when running `Terminal.init` with location turned off but permission enabled
Check before calling `Terminal.init` that you have location permission and that you have the location service turned on

**Comment by kekko7072** [comment]
hi @BreX900  thank you for your response really appreciated. From you response i tested and i see that in this board the service location is not reachable from flutter and android, there is a way to use this package and bypass that requirement?

**Comment by SimoneBressan** [comment]
Hi, It doesn't depend on my package, try contacting stripe support or open an issue on their [sdk](https://github.com/stripe/stripe-terminal-android)

**Comment by erolisdev** [comment]
Hi everyone @kekko7072 @BreX900,
Can you provide some insights on whether a solution has been found for this issue?

**Comment by kekko7072** [comment]
Hi @erolisdev, i discovered that geolocation it's mandatory but this board doesn't have it working so i implemented a platform channel to mock location so app can work. If you want you can also use application to mock location like [this one](https://apkcombo.com/it/gps-connector/de.pilablu.gpsconnector/download/apk). 
I suggest you to test using this app for mock location and then implement your own mock location using platform channel in flutter for andorid, it's easy but a little strange at the beginning.

**Comment by erolisdev** [comment]
@kekko7072 Thank you for your response. While working on a device with the "rk3568 r" card, I initially encountered the same error as you. However, after installing Google Maps on the device through Google Play, I noticed that it was able to receive location services and accurately determine the location. Everything returned to normal after making a few adjustments to the Android location settings.
