### ISSUE TITLE
incompatibleReader

### ISSUE THREAD

**Issue by SERDARPINAR** [BreX900/mek-packages#39]
hi mate..
im working your perfect package.. again thank you so much about it.
but when i change the connected reader then im getting incompatibleReader error. 

for example. i have. 2 buttons on the widget
First button => Tap to Pay button
Second button => USB Reader button

first when i click the first button everything is ok. then after process when i click to second button then getting error.

every each buttons when click 
1. first disconnect reader
2. discovery reader
3. connect to reader

i hope i could explain..

**Comment by BreX900** [comment]
Please post the error with more information, such as the entire error with the stacktrace, a piece of code where the error is generated, whether you are using an android or ios device and the phone model.
I also remember to try the sample app to see if you get the same problem
Thanks

**Comment by SERDARPINAR** [comment]
thanks mate. i fix it.  but i have another problem with apple. this problem not about your package. your package is peerfect. i think maybe you help me..  can you check this link. 
https://developer.apple.com/forums/thread/740401

thanks again
