### ISSUE TITLE
[PlatformException] "...required providing that Connected Account's ID in SCPLocalMobileConnectionConfiguration""

### ISSUE THREAD

**Issue by jermaine-uome** [BreX900/mek-packages#50]
Hello folks,

Firstly thanks for the hard work on this library. We have it working on Android and soon to push to prod. While testing on iOS we noticed that calling the `retrievePaymentIntent(clientSecret)` method on the `Terminal` object returns a `PaymentIntent` object that omits certain required fields from the initial payment intent created via our backend service. 

When attempting to pass that payment intent object to `collectPaymentMethod(...)` we get the following error:

> A required parameter was invalid or missing. Collecting a PaymentMethod for a PaymentIntent `on_bahalf_of` a Connected Account required providing that Connected Account's ID in `SCPLocalMobileConnectionConfiguration`

I noticed while digging in this package's codebase I found that these fields have been set to `nil` in **`stripe_terminal/ios/Classes/Mappings/PaymentIntentMappings.swift`**

* amountCapturable
* amountReceived
* applicationFeeAmount
* clientSecret
* onBehalfOf 

I tried a workaround of instanting a `PaymentIntent` object while passing those missing values manually using the payment intent object returned from our backend:

```
PaymentIntent(
  amountCapturable: rawIntent['amount_capturable'),
  onBehalfOf: rawIntent['on_behalf_of'],
 ...
 ...
)
```

Sadly this did not resolve the issue. Your help including any suggestions would be appreciated. 

Thanks so much

**Comment by BreX900** [comment]
I am not passing them because on the IOS intent those fields are not present. There is nothing I can do about it 

> A required parameter was invalid or missing. Collecting a PaymentMethod for a PaymentIntent on_bahalf_of a Connected Account required providing that Connected Account's ID in SCPLocalMobileConnectionConfiguration
The problem you're citing is definitely not for what I'm returning, at most the problem is for what I'm sending to Stripe to create a PaymentIntent.
Yes, there are some parameters missing for connecting to a`LocalMobileReader `. I believe you can configure them directly from your backend by passing them to the creation of a `PaymentIntent` https://stripe.com/docs/api/payment_intents/create . Also it should already be supported for the`PaymentIntent ` creation method by my plugin: `Terminal.createPaymentIntent`

```swift
extension PaymentIntentParametersApi {
    func toHost() throws -> PaymentIntentParameters {
        let b = PaymentIntentParametersBuilder(
                amount: UInt(amount),
                currency: currency
            )
            .setPaymentMethodTypes(paymentMethodTypes.map { $0.toHost() })
            .setCaptureMethod(captureMethod.toHost())
            .setMetadata(metadata)
            .setStripeDescription(description)
            .setStatementDescriptor(statementDescriptor)
            .setStatementDescriptorSuffix(statementDescriptorSuffix)
            .setReceiptEmail(receiptEmail)
            .setCustomer(customerId)
            .setApplicationFeeAmount(applicationFeeAmount?.nsNumberValue)
            .setTransferDataDestination(transferDataDestination)
            .setTransferGroup(transferGroup)
            .setOnBehalfOf(onBehalfOf)
            .setSetupFutureUsage(setupFutureUsage?.toHost())
        if let it = paymentMethodOptionsParameters { b.setPaymentMethodOptionsParameters(try it.toHost()) }
        return try b.build()
    }
}
```
