### ISSUE TITLE
physical device gets connected but app gets stuck on connecting

### ISSUE THREAD

**Issue by mhdaslam790** [BreX900/mek-packages#52]
Hey  I am trying to connect an physical device it's get connected with the device but the example app gets stuck to the connecting
. While the simulator device gets connected and the rest of the flow works just fine.

**Comment by BreX900** [comment]
Hi, missing information such as device and reader.
Are all permissions enabled? Are bluethoot and Gps(Location) services turned on? 
Could this be the problem?
https://github.com/BreX900/mek-packages/issues/49
