### ISSUE TITLE
Terminal update

### ISSUE THREAD

**Issue by smileev-rps** [BreX900/mek-packages#55]
Hi @BreX900, thanks for this lib.
Can I ask you to make new methods for simulated updates of terminal and methods for nofying about update process like estimatedUpdateTime

**Comment by BreX900** [comment]
You can simulate some cases via `Terminal.setSimulatorConfiguration`. Cases not covered by this method will not be considered since they are not official of the android and ios sdks

**Comment by smileev-rps** [comment]
Thanks for the answer
If i'm not wrong the requested information _estimatedUpdateTime_ had been added to android and ios sdks:
https://stripe.com/docs/terminal/payments/connect-reader?terminal-sdk-platform=ios&reader-type=bluetooth#update-reader
https://stripe.com/docs/terminal/payments/connect-reader?terminal-sdk-platform=android&reader-type=bluetooth#update-reader

It will be really greate if you could add it beacause for now it's hard to know the progress of updating. 
Or I wasn't attentive and didn't notice this method

**Comment by BreX900** [comment]
@smileev-rps Sorry for the delayed response, but you can find the same implementation in the `PhysicalReaderDelegate` dart class via the methods `onReportAvailableUpdate`, `onStartInstallingUpdate`, `onReportReaderSoftwareUpdateProgress` and `onFinishInstallingUpdate`
Then implement your custom delegate. Pass it to the `Terminal.connectTo*` methods and you're done!
