### ISSUE TITLE
cancel action

### ISSUE THREAD

**Issue by SERDARPINAR** [BreX900/mek-packages#6]
hi. when i start the collectionn on reader and then how can i cancel reader action..

**Comment by BreX900** [comment]
@SERDARPINAR You can stop the search for readers by simply stopping listening to the stream (StreamSubscription.cancel).
I will also add another option to do this, adding the method to stop searching for readers in the next release. Thank you very much for the tip

**Comment by SERDARPINAR** [comment]
hi.. i was try stop listening. but reader screen not changing..  still waiting tap to card.. when will be add cancel action. if you fix it quick i will make big tip.. because very important for me

**Comment by BreX900** [comment]
Sorry, I'm not sure I'm understanding.
Are you running StripeTerminal.collectPaymentMethod?
If yes, to cancel this method returns a CancellableFuture.
So for example you can do this:
'''dart
final collecting = terminal.collectPaymentMethod();
// Cancel collect payment method
await collecting.cancel()
// Collected payment method
final paymentIntent = await collecting;
'''

If that's not what you're talking about, could you explain further?

**Comment by SERDARPINAR** [comment]
hi again.. That's not what we mean. we seeing amount on the physcal reader screen after terminal.collectpaymentmethod() . ok up to here.  but when cancel the paymentintent then  physcal reader screen still waiting payment. physcal screen reader not clearing. do you understand me.  thannks

**Comment by BreX900** [comment]
If you can write a code example that would be great.

I think I understand that after calling `terminal.collectPaymentMethod` you call `terminal.cancelPaymentIntent` (frontend/backend does not change).
In this case only the payment intent is cancelled, you will have to cancel `terminal.collectPaymentMethod` with the previous example

The payment intent is separated from the state of the reader

Perhaps you could find more information on the official [android](https://github.com/stripe/stripe-terminal-android)/[ios](https://github.com/stripe/stripe-terminal-ios) sdks. I understand that you expect certain behaviors from my package. But my package is 1 to 1 with android/ios sdk

**Comment by SERDARPINAR** [comment]
hi. again. can you give me your email. i will send a video for process

**Comment by BreX900** [comment]
I don't think I understand much without seeing the code.
You can also post the video here, prefer not to share my email in a public channel

You could also try emulating the problem with native sdk. If you encounter the problem even with native sdk then you should contact Stripe support

**Comment by SERDARPINAR** [comment]
hi.. 

I describe the problem step by step.

1. payment process is initiated. (paymentIntent).
2. transaction is sent to the physical card reader.
3. The amount to be paid appears on the card reader screen.
4. At this time, I want to cancel the operation. (without reading any card on the card reader) . but the card reader is waiting for an action. The payment amount is still displayed on the screen.

Let me explain with a second example. For example, you went to mcdonalds.. you ordered at a McDonalds. employer sent payment to authorized card reader. but at that time you wanted to give up and pay cash. At this time, even if I cancel the transaction then the card reader is waiting for an action. (swipe, tap, etc.)

I hope it was clearer. Thanks for your help. but I haven't seen anyone who can do this on flutter yet.

**Comment by SERDARPINAR** [comment]
thank you.. but we already tryed it. but not working..  yes payment canceled but reader scrreen still waiting action.(tap,swap....) 
we asked to stripe support. but they dont have support for flutter.   and very interesting nobody fixit.. still seaching for soluition.

**Comment by SERDARPINAR** [comment]
please check link (video)
https://we.tl/t-HhYwkT0wwT

**Comment by SERDARPINAR** [comment]
https://www.youtube.com/watch?v=aeNpp66_yAU
this is stripe support video for cancel reader action. but not work with flutter.  if you integrate this java to flutter then i guess will be work..  please check..

**Comment by SimoneBressan** [comment]
@SERDARPINAR I updated the sample app by making the "Cancel Collecting Payment Method" button appear instead of "Collect Payment Method." Can you try?

The solution I implemented is as follows:
```dart
final collecting = terminal.collectPaymentMethod();
// Cancel collect payment method
await collecting.cancel()
```

**Comment by BreX900** [comment]
@SERDARPINAR  I updated the sample app by making the "Cancel Collecting Payment Method" button appear instead of "Collect Payment Method." Can you try?

The solution I implemented is as follows:
```dart
final collecting = terminal.collectPaymentMethod();
// Cancel collect payment method
await collecting.cancel()
```

**Comment by SERDARPINAR** [comment]
thanks.. i will try. and will back you

**Comment by SERDARPINAR** [comment]
your perfect mate... this worked.  i will inntegrrate my own code and then i will turn you if any problem. but worked your example code. thanks.. your save my days..

**Comment by SERDARPINAR** [comment]
hi again..everything looks good..  can you tell me please how can we donate you ?  ...thanks again
