### ISSUE TITLE
Error on building the app in android emulator, when I add mek_stripe_terminal package.

### ISSUE THREAD

**Issue by mackymangampo** [BreX900/mek-packages#65]
I added the mek_stripe_terminal: ^3.4.0 on our app in **pubspec.yaml**, then in the **android/app/build.gradle** I upgrade the **minSdkVersion to 26**. But I don't why I'm facing an build failed on emulator but on the ios simulator doesn't have problem. I just follow the readme step on the pub.dev ref: https://pub.dev/packages/mek_stripe_terminal. 

Hopefully anyone can answer my issue. 

My Java version as of now is **OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)**

**Flutter doctor**
![image](https://github.com/BreX900/mek-packages/assets/44796954/a5b10022-3542-4ed7-b50c-0badf098eb30)

**BUILD ISSUE ON EMULATOR**: 
![image](https://github.com/BreX900/mek-packages/assets/44796954/190f9c5c-072f-40ac-bbbb-41e3053e0ec0)

**Comment by SahilSharma2710** [comment]
hey @rennyrocha how can we update the kotlin version ??
I have tried it but it's not working
