### ISSUE TITLE
Unhandled Exception: TerminalException: localMobileDebugNotSupported

### ISSUE THREAD

**Issue by SERDARPINAR** [BreX900/mek-packages#70]
please help..ios no problem.  but android getting error

Unhandled Exception: TerminalException: localMobileDebugNotSupported

**Comment by SERDARPINAR** [comment]
hi brother. did you see this qustions. do you have any opinion

**Comment by BreX900** [comment]
You cannot connect to localMobile in debug unless you simulate it
