### ISSUE TITLE
Unhandled Exception: TerminalException: localMobileDebugNotSupported on android

### ISSUE THREAD

**Issue by SERDARPINAR** [BreX900/mek-packages#76]
hi mate. please help. when runing on android im getting this error. but iphone is working perfect. thanks

**Comment by MaksimDeve** [comment]
On Android it needs to be launched in the release, it seems that the reader does not work in the debug

**Comment by SahilSharma2710** [comment]
hey @SERDARPINAR , have u able to run this package for android ??
I am having some issues on the collect payment screen, the amount is not showing . Can u share some insights

**Comment by BreX900** [comment]
In debug/profile mode you need to switch `isSimulated` to `true`

```
    final configuration = switch (_discoveringMethod) {
      DiscoveryMethod.bluetoothScan => BluetoothDiscoveryConfiguration(
          isSimulated: _isSimulated,
        ),
      DiscoveryMethod.bluetoothProximity => BluetoothProximityDiscoveryConfiguration(
          isSimulated: _isSimulated,
        ),
      DiscoveryMethod.handOff => const HandoffDiscoveryConfiguration(),
      DiscoveryMethod.internet => InternetDiscoveryConfiguration(
          isSimulated: _isSimulated,
        ),
      DiscoveryMethod.localMobile => LocalMobileDiscoveryConfiguration(
          isSimulated: _isSimulated,
        ),
      DiscoveryMethod.usb => UsbDiscoveryConfiguration(
          isSimulated: _isSimulated,
        ),
    };
```

**Comment by SERDARPINAR** [comment]
thanks. but when i setup simulated true then will not continue the actual processing. ???

**Comment by SERDARPINAR** [comment]
> Hey@SERDARPINAR, bu paketi android için çalıştırabildiniz mi? Ödeme toplama ekranında bazı sorunlar yaşıyorum, tutar gösterilmiyor. Bazı görüşlerinizi paylaşabilir misiniz?

no. i didnt. but ios working
