### ISSUE TITLE
[iOS Tap To Pay] This feature is currently not available for the selected reader.

### ISSUE THREAD

**Issue by Vitaly-V** [BreX900/mek-packages#8]
First and foremost, thank you for such an excellent product!

I'm having a problem with Tap to Pay on iOS.
Could you please assist me in figuring it out?

On Android, everything works.
Apple granted me permission to utilize the ProximityReader APIs.
The project appears to be correctly set up. I created project.entitlements added "com.apple.developer.proximity-reader.payment.acceptance" to the project.entitlements and added the full path in Code Signing Entitlements.
To be sure that I have all the permissions and that I set the project well, I installed the official Stripe iOS SDK, and Tap to Pay works on exact same device (tested SDK versions 3.0.0 and 2.23.1)
 
Log:
 
`2023-09-14 12:50:18.813753+0200 Runner[3779:1281223] Metal API Validation Enabled
2023-09-14 12:50:19.291982+0200 Runner[3779:1281223] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
2023-09-14 12:50:19.373268+0200 Runner[3779:1281644] flutter: The Dart VM service is listening on http://127.0.0.1:55715/3wDt3bh-UNE=/
2023-09-14 12:50:21.102277+0200 Runner[3779:1281613] [VERBOSE-2:shell.cc(1004)] The 'StripeTerminalHandlers' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
2023-09-14 12:50:23.066992+0200 Runner[3779:1281609] [ProximityReader] User cancelled
2023-09-14 12:50:30.290732+0200 Runner[3779:1281223] Can't find keyplane that supports type 4 for keyboard iPhone-PortraitTruffle-NumberPad; using 27315_PortraitTruffle_iPhone-Simple-Pad_Default
2023-09-14 12:50:32.787972+0200 Runner[3779:1281617] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(, This feature is currently not available for the selected reader., Error Domain=com.stripe-terminal Code=1880 "This feature is currently not available for the selected reader." UserInfo={NSLocalizedDescription=This feature is currently not available for the selected reader., com.stripe-terminal:Message=This feature is currently not available for the selected reader.}, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
#2      _$StripeTerminalPlatform.createPaymentIntent (package:mek_stripe_terminal/src/platform/stripe_terminal_platform.api.dart:214:22)
<asynchronous suspension>
#3      StripeTerminal.createPaymentIntent (package:mek_stripe_terminal/src/stripe_terminal.dart:288:7)
<asynchronous suspension>
#4      _TapToPayState._pay (package:shoppingapp/src/sample_feature/tap_to_pay.dart:150:16)
<asynchronous suspension>`

Code:
```
import 'dart:convert';
import 'dart:developer';
import 'dart:io';

import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:mek_stripe_terminal/mek_stripe_terminal.dart';
import 'package:permission_handler/permission_handler.dart';

class TapToPay extends StatefulWidget {
  const TapToPay({
    super.key,
  });

  static const routeName = '/';

  @override
  State<TapToPay> createState() => _TapToPayState();
}

class _TapToPayState extends State<TapToPay> {
  StripeTerminal? stripeTerminal;
  @override
  void initState() {
    super.initState();
    _init();
  }

  var _readers = [];
  var _amount = 0;
  var _error = "";
  var _isSuccess = false;

  void _init() async {
    setState(() {
      _error = "";
      _isSuccess = false;
    });
    final permissions = [
      Permission.locationWhenInUse,
      Permission.bluetooth,
      if (Platform.isAndroid) ...[
        Permission.bluetoothScan,
        Permission.bluetoothConnect,
      ],
    ];
    await permissions.request();
    stripeTerminal = await StripeTerminal.getInstance(
      fetchToken: getStripeToken,
    );
    stripeTerminal!
        .discoverReaders(
            discoveryMethod: DiscoveryMethod.localMobile, simulated: false)
        .listen((List readers) {
      setState(() => _readers = readers);
      _connectReader();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Padding(
            padding: const EdgeInsets.all(50),
            child: TextField(
              textAlign: TextAlign.center,
              decoration: const InputDecoration(
                border: OutlineInputBorder(),
                labelText: 'Amount',
              ),
              keyboardType: TextInputType.number,
              onChanged: (value) {
                setState(() {
                  _amount = int.parse(value);
                });
              },
            ),
          ),
          const SizedBox(
            height: 20,
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.green, // background
            ),
            onPressed: _pay,
            child: const Text(
              'Pay',
              style: TextStyle(color: Colors.white, fontSize: 20),
            ),
          ),
          const SizedBox(
            height: 50,
          ),
          if (_isSuccess)
            const Text('SUCCESS', style: TextStyle(color: Colors.green)),
          Padding(
            padding: const EdgeInsets.all(20),
            child: Text(
              _error,
              style: const TextStyle(color: Colors.red),
            ),
          ),
        ],
      ),
    );
  }

  Future<String> getStripeToken() async {
    var response = await Dio().get(
        'https://YOUR_BACKEND/getTerminalToken');
    var token = jsonDecode(response.data);
    log(token['secret']);
    return token['secret'];
  }

  _connectReader() async {
    try {
      if (stripeTerminal != null && _readers.isNotEmpty) {
        await stripeTerminal!.connectMobileReader(_readers[0],
            locationId: "YOUR_LOCATION_ID");
      }
    } catch (e) {
      log(e.toString());
      setState(() {
        _error = e.toString();
      });
    }
  }

  void _pay() async {
    setState(() {
      _error = "";
      _isSuccess = false;
    });
    try {
      var pip = PaymentIntentParameters(
          amount: _amount * 100,
          currency: 'usd',
          captureMethod: CaptureMethod.automatic,
          paymentMethodTypes: [
            PaymentMethodType.card,
            PaymentMethodType.cardPresent
          ]);
      var pi = await stripeTerminal!.createPaymentIntent(pip);
      final processablePaymentIntent =
          await stripeTerminal!.collectPaymentMethod(pi);
      final capturablePaymentIntent =
          await stripeTerminal!.processPayment(processablePaymentIntent);
      setState(() {
        _isSuccess = true;
      });
    } on TerminalException catch (e) {
      print(e);
      setState(() {
        _error = e.message!;
      });
    }
  }
}
```

**Comment by BreX900** [comment]
I released version 2.1.2 with the fix for tokens and more. Could you try?

I don't have much way to test the ios part at the moment but it should be correct. If there are other problems do not hesitate to report them to me. Thanks

> Enclose the error with three quotation marks to make it clearer

**Comment by Vitaly-V** [comment]
Thank you for your quick response.

Through debugging, I found out that

The `stripeTerminal.discoverReaders` stream never returns readers for iOS, even if `simulated: true` is used. Moreover, even in debug mode.

It's impossible to see iOS logs if you run flutter run --release.
But this is what I receive when I launch the app via xCode.

```
2023-09-15 10:09:53.423438+0200 Runner[4239:1487666] Metal API Validation Enabled
2023-09-15 10:09:53.586544+0200 Runner[4239:1487666] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
2023-09-15 10:09:53.648020+0200 Runner[4239:1487987] flutter: The Dart VM service is listening on http://127.0.0.1:61113/oNZmK9QuzuE=/
2023-09-15 10:09:55.269119+0200 Runner[4239:1487957] [ProximityReader] User cancelled
```
This is what I receive when I tap the PAY button, which calls the `_pay()` method from the code I provided above.
```
2023-09-15 10:12:31.031085+0200 Runner[4239:1487965] [VERBOSE-2:dart_vm_initializer.cc(41)] 
Unhandled Exception: PlatformException(, This feature is currently not available for the selected reader., 
Error Domain=com.stripe-terminal Code=1880 "This feature is currently not available for the selected reader." UserInfo={NSLocalizedDescription=This feature is currently not available for the selected reader., com.stripe-terminal:Message=This feature is currently not available for the selected reader.}, null)

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
#2      _$StripeTerminalPlatform.createPaymentIntent (package:mek_stripe_terminal/src/platform/stripe_terminal_platform.api.dart:214:22)
<asynchronous suspension>
#3      StripeTerminal.createPaymentIntent (package:mek_stripe_terminal/src/stripe_terminal.dart:288:7)
<asynchronous suspension>
#4      _TapToPayState._pay (package:shoppingapp/src/sample_feature/tap_to_pay.dart:152:16)
<asynchronous suspension>
```

The error `This feature is currently not available for the selected reader`  seems reasonable because there is no reader attached.

**Comment by Vitaly-V** [comment]
I'm not sure where the `[ProximityReader] User cancelled` message came from. 
Perhaps you could help me figure it out?

**Comment by BreX900** [comment]
Sorry for the delay, I'm doing some tests but the stripe key I have is not enabled for stripe terminal on ios
I'll keep you updated

**Comment by BreX900** [comment]
@Vitaly-V I solved the problems with discoveryReaders. Now in version 2.1.3 you should be able to find the readers
Give me feedback if you can connect to a reader

**Comment by Vitaly-V** [comment]
@BreX900, thank you for your assistance.

Now the app is able to discover readers.
However, when connecting the reader, it throws a PlatformException 

```PlatformException(, The operation couldn’t be completed. (mek_stripe_terminal.PlatformError error 1.), mek_stripe_terminal.PlatformError, null)```


Before connecting I check that stripeTerminal  is not null and readers are not empty
```
  _connectReader() async {
    try {
      if (stripeTerminal != null && _readers.isNotEmpty) {
        await stripeTerminal!
            .connectMobileReader(_readers[0], locationId: "location_id");
      }
    } catch (e) {
      log(e.toString());
    }
  }
```

**Comment by BreX900** [comment]
@Vitaly-V You can try version 2.1.4. All bugs should be fixed

**Comment by Vitaly-V** [comment]
@BreX900, thank you! Now everything works as expected!
