### ISSUE TITLE
Amount not showing on payment screen android

### ISSUE THREAD

**Issue by SahilSharma2710** [BreX900/mek-packages#81]
Hey I have been trying to create a simulated payment through tap & pay , the payment is getting successful but i am unable to show the amount on the screen 
c.c. @kuamanet @ManuInNZ @BreX900 @GabM3 @jacopofranza 
 
![Screenshot_20240718-182653_stripe_terminal_example](https://github.com/user-attachments/assets/9b538645-139d-401d-abbe-9c25a7c69868)

this is how i am creating intent 
![Screenshot 2024-07-19 at 4 32 41 PM](https://github.com/user-attachments/assets/abc90952-6b71-4a5a-ba40-3b33248498c6)

This is how i am calling 
`    await _createPaymentIntent(
      _terminal!,
      '0.80',
      5,
    );`

**Comment by BreX900** [comment]
Uses version `3.7.0` of `mek_stripe_terminal`
See android [CHANGELOG.md](https://github.com/stripe/stripe-terminal-android/blob/master/CHANGELOG.md#tap-to-pay-localmobile-1) for more info
